# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import typing
__all__ = [
    "ExfilDetectorEngine",
    "py_scan_container",
]

@typing.final
class ExfilDetectorEngine:
    r"""
    Persistent engine that parses config once at init and reuses it across scans.
    """
    def __new__(cls, config: typing.Any) -> ExfilDetectorEngine: ...
    def scan(self, container: typing.Any) -> tuple[builtins.int, typing.Any, list]:
        r"""
        Scan a container using the pre-parsed config. No per-call config parsing.
        """

def py_scan_container(container: typing.Any, config: typing.Any) -> tuple[builtins.int, typing.Any, list]:
    r"""
    Backward-compatible bare function — creates a temporary engine per call.
    """
