# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import typing
__all__ = [
    "EvalDimension",
    "EvalResult",
    "RateLimiterEngine",
    "RateLimiterPluginCore",
]

@typing.final
class EvalDimension:
    r"""
    The outcome of a single active dimension, exposed to Python for
    per-dimension inspection (e.g. which dimension blocked the request).
    """
    @property
    def remaining(self) -> builtins.int:
        r"""
        Requests remaining for this active dimension.
        """
    @property
    def reset_timestamp(self) -> builtins.int:
        r"""
        Unix timestamp when this dimension resets or refills.
        """
    @property
    def retry_after(self) -> typing.Optional[builtins.int]:
        r"""
        Seconds until retry — populated only for blocked dimensions.
        """

@typing.final
class EvalResult:
    r"""
    The aggregated result returned to Python via `evaluate_many()`.
    
    Contains the most restrictive outcome across all active dimensions
    (min remaining, earliest unblock among blocked dimensions — matching
    Python `_select_most_restrictive`).
    """
    @property
    def allowed(self) -> builtins.bool:
        r"""
        `True` if all active dimensions allow the request.
        """
    @property
    def limit(self) -> builtins.int:
        r"""
        Configured limit for the most restrictive active dimension.
        """
    @property
    def remaining(self) -> builtins.int:
        r"""
        Remaining requests for the most restrictive active dimension.
        """
    @property
    def reset_timestamp(self) -> builtins.int:
        r"""
        Unix timestamp when the most restrictive dimension resets.
        """
    @property
    def retry_after(self) -> typing.Optional[builtins.int]:
        r"""
        Seconds until reset — populated only when `allowed == False`.
        """
    @property
    def violated_dimensions(self) -> builtins.list[EvalDimension]:
        r"""
        Per-dimension outcomes that were blocked for this request.
        """
    @property
    def allowed_dimensions(self) -> builtins.list[EvalDimension]:
        r"""
        Per-dimension outcomes that still allowed this request.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class RateLimiterEngine:
    r"""
    High-performance rate limiter engine.
    
    Construct once per plugin instance (`__init__`), then call
    `check()` / `check_async()` on every hook invocation.
    
    Backend is selected at init time from the config dict:
    - `backend: "memory"` (default) — in-process counting via `MemoryStore`
    - `backend: "redis"` — Rust owns the Redis connection; same batch Lua
      scripts as the Python `RedisBackend`, one EVAL per hook invocation
    """
    def __new__(cls, config: dict) -> RateLimiterEngine:
        r"""
        Construct from the Python config dict.
        
        Parses all rate strings and normalises `by_tool` keys at init time —
        never on the request path (IFACE-01, IFACE-05).
        
        Extra keys consumed here (not part of `EngineConfig`):
        - `backend`: `"memory"` (default) or `"redis"`
        - `redis_url`: required when `backend = "redis"`
        - `redis_key_prefix`: key namespace prefix (default `"rl"`)
        - `fail_mode`: `"open"` (default) or `"closed"` — handled by the
          plugin shim, but accepted here so it doesn't trip the unknown-key
          warning below.
        
        Any other key in the dict is logged at WARN so misspellings (e.g.
        `redis_ur` instead of `redis_url`) surface visibly instead of being
        silently ignored.
        """
    def check(self, user: builtins.str, tenant: typing.Optional[builtins.str], tool: builtins.str, now_unix: builtins.int, include_retry_after: builtins.bool, context_prefix: typing.Optional[builtins.str]) -> tuple[builtins.bool, dict, dict]:
        r"""
        High-level check: builds dimension keys internally, evaluates, and
        returns pre-built Python dicts for headers and metadata.
        
        This eliminates all per-attribute PyO3 accesses on the Python side.
        The Python wrapper calls this once per hook invocation.
        
        Returns `(allowed, headers_dict, meta_dict)`.
        
        When `context_prefix` is provided (e.g. a team/tenant ID), it is
        prepended to every dimension key so that separate plugin instances
        for different tenants use isolated Redis counters instead of sharing
        a single key namespace.
        
        **Note:** The Redis backend arm uses `block_on()` on a dedicated Tokio
        runtime, which would deadlock if called from within a Tokio context.
        The Python wrapper routes Redis to `check_async()` instead; this sync
        path is intended for the memory backend.  The `debug_assert` below
        guards against accidental misuse.
        """
    def check_async(self, user: builtins.str, tenant: typing.Optional[builtins.str], tool: builtins.str, now_unix: builtins.int, include_retry_after: builtins.bool, context_prefix: typing.Optional[builtins.str]) -> typing.Any:
        r"""
        Async variant of `check()` for Redis-backed deployments.
        
        Returns an awaitable that resolves to `(allowed, headers_dict, meta_dict)`.
        """

@typing.final
class RateLimiterPluginCore:
    def __new__(cls, config: dict) -> RateLimiterPluginCore: ...
    def shutdown(self) -> None:
        r"""
        Release backend-held resources (e.g. the cached Redis multiplexed
        connection). Called by the Python shim's `shutdown()` when the plugin
        framework tears the plugin down.
        """
    def prompt_pre_fetch(self, payload: typing.Any, context: typing.Any) -> typing.Any: ...
    def tool_pre_invoke(self, payload: typing.Any, context: typing.Any) -> typing.Any: ...



def compat_default_config() -> dict: ...
def compat_parse_rate(rate: builtins.str) -> tuple[builtins.int, builtins.int]: ...
