# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import typing

__all__ = [
    "URLReputationEngine",
    "URLReputationPluginCore",
    "URLReputationResult",
]


@typing.final
class URLReputationResult:
    continue_processing: bool
    violation: typing.Any


@typing.final
class URLReputationEngine:
    def __new__(cls, config: dict) -> URLReputationEngine: ...
    def validate_url(self, url: str) -> URLReputationResult: ...


@typing.final
class URLReputationPluginCore:
    def __new__(cls, config: dict) -> URLReputationPluginCore: ...
    def resource_pre_fetch(self, payload: typing.Any, context: typing.Any) -> typing.Any: ...
