# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import typing

__all__ = [
    "PluginViolation",
    "URLPluginResult",
    "URLReputationPlugin",
]


@typing.final
class PluginViolation:
    reason: str
    description: str
    code: str
    details: typing.Optional[dict[str, str]]


@typing.final
class URLPluginResult:
    continue_processing: bool
    violation: typing.Optional[PluginViolation]


@typing.final
class URLReputationPlugin:
    def __new__(cls, config: typing.Any) -> URLReputationPlugin: ...
    def validate_url(self, url: str) -> URLPluginResult: ...
    def validate_url_py(self, url: str) -> dict[str, typing.Any]: ...
