# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import typing
__all__ = [
    "SecretsDetectionPluginCore",
    "py_scan_container",
]

@typing.final
class SecretsDetectionPluginCore:
    def __new__(cls, config: typing.Any) -> SecretsDetectionPluginCore: ...
    def prompt_pre_fetch(self, payload: typing.Any, _context: typing.Any) -> typing.Any: ...
    def tool_post_invoke(self, payload: typing.Any, _context: typing.Any) -> typing.Any: ...
    def resource_post_fetch(self, payload: typing.Any, _context: typing.Any) -> typing.Any: ...

def py_scan_container(container: typing.Any, config: typing.Any) -> tuple[builtins.int, typing.Any, list]: ...
